# Generated by Django 5.1.3 on 2024-12-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_availablecolor_available_alter_availablecolor_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablecolor',
            options={'ordering': ['available']},
        ),
        migrations.AlterField(
            model_name='availablecolor',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
